name: PR Deploy Storybook to GitHub Pages

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    env:
      PREVIEW_DEST_PATH: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr/${{ github.head_ref }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: npm

      - run: npm ci

      - run: npm run storybook:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./storybook-static
          destination_dir: pr/${{ github.head_ref }}
          prune: true

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Storybook Preview

      - name: Comment Storybook preview URL
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ### 🚀 Storybook Preview
            ${{ env.PREVIEW_DEST_PATH }}/
